services:
  kost-db:
    image: postgres:18-alpine
    container_name: kost-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kost_database 
      POSTGRES_USER: kost_user   
      POSTGRES_PASSWORD: P@ssw0rd
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data

  laravel-api:
    build: 
      context: ./server
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel-api
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./server:/var/www/html
    depends_on:
      - kost-db

  kost-nginx:
    image: nginx:alpine
    container_name: kost-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./server:/var/www/html
      - ./server/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-api

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  db-data: